#!/usr/bin/python

import glob
from jsmin import jsmin
import sys

data = ""
with open('src/three_js/three.min.js') as js_file:
	data += js_file.read();

for filename in glob.iglob('./**/*.js', recursive=True):
	if filename == 'src/three_js/three.min.js': continue
	with open(filename) as js_file:
			data += js_file.read();

minified = jsmin(data, quote_chars="'\"`")
with open('he3.min.js', 'w') as fh:
	fh.write(minified);
