#!/usr/bin/python

import glob
from jsmin import jsmin
import sys

data = ""
for filename in glob.iglob('./**/*.js', recursive=True):
	with open(filename) as js_file:
			data += js_file.read();

minified = jsmin(data, quote_chars="'\"`")
with open('he3.min.js', 'w') as fh:
	fh.write(minified);
